spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chood?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1609981289@qq.com
    password: tdfywuizwggrhicb
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false

server:
  port: 8081
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  servlet:
    context-path: /api
    session:
      timeout: 24h

upload:
  model: local
  local:
    path: D:/chood/upload/
    url: upload/
    enable-proxy: true
    proxy: /api/